aa

diff --git a/.github/workflows/ml_pipeline.yaml b/.github/workflows/ml_pipeline.yaml
--- a/.github/workflows/ml_pipeline.yaml
+++ b/.github/workflows/ml_pipeline.yaml
@@ -9,10 +9,46 @@ permissions:
 jobs:
   train_modal:
     runs-on: ubuntu-latest
-
     steps:
     - name: Checkout code
       uses: actions/checkout@v2
+
+    - name: az login using federated credentials
+      uses: azure/login@v1
+      with:
+        client-id: "6863db71-fcbf-4466-8046-997de5b919c3"
+        tenant-id: "9fc5e873-a267-48bf-a6dd-9c332cf29837"
+        subscription-id: "a5e53954-5571-4fa4-9dd5-bfc7eda513a4"
+
+    - name: Set up kubectl
+      uses: azure/setup-kubectl@v1
+      with:
+        version: 'latest'
+
+    - name: Get AKS credentials
+      run: az aks get-credentials --resource-group k8_modal_rg --name k8_modal_aks
+
+    - name: Get MLflow IP
+      id: get_ip
+      run: |
+        for i in {1..60}; do
+          IP=$(kubectl get svc mlflow-service -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
+          if [ -n "$IP" ]; then
+            echo "MLFLOW_SERVER_IP=$IP" >> $GITHUB_ENV
+            echo "MLFLOW_SERVER_IP=$IP"
+            exit 0
+          fi
+          echo "waiting for MLflow IP..."
+          sleep 10
+        done
+        echo "MLflow IP not found" >&2
+        exit 1
+
+    - name: Check MLflow health
+      run: |
+        curl --fail http://${{ env.MLFLOW_SERVER_IP }}:5000 || exit 1
+        echo "Using MLflow at http://${{ env.MLFLOW_SERVER_IP }}:5000"
+
 
     - name: Set up Python
       uses: actions/setup-python@v2
@@ -30,33 +66,13 @@ jobs:
         python chai-sutta-modal-mlflow/src/train_model.py
       env:
         MODEL_VERSION: v${{ github.run_number }}
-        MLFLOW_TRACKING_URI: ./mlruns
-
-    - name: Upload MLFLOW artifacts (debug)
-      uses: actions/upload-artifact@v4
-      with:
-        name: mlflow-${{ github.run_number }}
-        path: mlruns/
+        MLFLOW_TRACKING_URI: http://${{ env.MLFLOW_SERVER_IP }}:5000
 
     - name: artifact Modal upload
       uses: actions/upload-artifact@v4
       with:
-        name: models
+        name: models-${{ github.run_number }}
         path: chai-sutta-modal-mlflow/models/
-
-    - name: az login using federated credentials
-      uses: azure/login@v1
-      with:
-        client-id: "6863db71-fcbf-4466-8046-997de5b919c3"
-        tenant-id: "9fc5e873-a267-48bf-a6dd-9c332cf29837"
-        subscription-id: "a5e53954-5571-4fa4-9dd5-bfc7eda513a4"
-
-    - name: Upload MLflow logs to storage
-      run: |
-        az storage blob upload-batch \
-          -d chai-sutta-container/mlflow/v${{ github.run_number }} \
-          --account-name modalstorageacc \
-          -s ./mlruns
 
     - name: Upload model artifacts
       run: |
@@ -64,3 +80,5 @@ jobs:
           -d chai-sutta-container/models/v${{ github.run_number }} \
           --account-name modalstorageacc \
           -s ./chai-sutta-modal-mlflow/models
+
+  
